data_platform/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls  import url
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static

app_name = "data_platform"
urlpatterns = [
    url(r'^$', views.index_view.as_view(), name="index"),
    url(r'^accident_list/',views.get_accident_list.as_view(), name="accident_list"),
    url(r'^term_list/',views.get_term_list.as_view(), name="term_list"),
    url(r'^term/(?P<term_id>\d+)$', views.get_term_detail.as_view(), name="term_detail"),
    url(r'^download/',views.get_download.as_view(), name="download")
]

employee/urls.py
from django.urls import path 
from . import views 
 
urlpatterns = [ 
    path('register/', views.EmployeeRegistrationView.as_view(), name='employee_registration'), 
]

rmsdata/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from . import view
from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    url(r'^$', view.index),
    url(r'^data_platform/', include('data_platform.urls')),
    path('employee/', include('employee.urls')),
]

data_platform/models.py
from django.db import models
from taggit.managers import TaggableManager

# Create your models here.

#单独建立的用户模型
class  user(models.Model):
  id = models.AutoField(primary_key = True)
  name =  models.CharField(max_length = 100)
  info = models.CharField(max_length = 200, default = "na")


#机型数据模型
class acmodel(models.Model):
    id = models.AutoField(primary_key = True)
    basic_acmodel = models.CharField("基本型号", max_length = 100)
    expanded_acmodel = models.CharField("扩展型号", max_length = 100)
    if_intra_ac = models.BooleanField(default = False)

    def __str__(self):
        return (self.basic_acmodel)

#事故数据模型
class accident(models.Model):
  id = models.AutoField(primary_key = True)
  title = models.CharField("标题", max_length=200)
  date = models.DateField("发生时间")
  content = models.TextField("事件描述")
  acmodel = models.ForeignKey(acmodel, on_delete = models.CASCADE)

  def __str__(self):
    return (self.title)

#术语定义部分内容
class term(models.Model):
    id = models.AutoField(primary_key = True)
    title = models.CharField("概词条念", max_length = 200)
    content = models.TextField("词条说明")
    acmodel = models.ForeignKey(acmodel, on_delete = models.CASCADE, limit_choices_to={'if_intra_ac': True})
    tag = TaggableManager("标签",blank=True)
    source = models.TextField("词条来源",blank=True)

    def __str__(self):
        return (self.title)
    
#数据来源说明模型    
class data_source(models.Model):
    id = models.AutoField(primary_key = True)
    #The title here represents the name of data source that has a series of data tables, each of them gathered in different time.
    title = models.CharField("title of data table", max_length = 200)
    slug = models.SlugField(max_length=200, unique=True)
    acmodel = models.ForeignKey(acmodel, on_delete = models.CASCADE)
    source_interpretation = models.CharField("Interpretation of the data source", max_length = 300)
                                 
    def __str__(self):
        return (self.title)

#历史数据表模型
class data_address(models.Model):                                                     
    id = models.AutoField(primary_key = True)
    title = models.CharField("download file address", max_length = 200)
    slug = models.SlugField(max_length=200, unique=True)
    date = models.DateField("发生时间")
    data_source = models.ForeignKey(data_source, on_delete = models.CASCADE)
                                                                    
    def __str__(self):
        #resolve the display problem 'Data_addresss' in admin's frontpage, but failed.
        return (self.title+'e')

employee/models.py
from django.db import models

# Create your models here.

data_platform/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
#import markdown
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin

from data_platform.models import accident
from data_platform.models import term


class index_view(ListView):
	template_name = "index.html"
	context_object_name = "text"

	def get_queryset(self):
		now = datetime.datetime.now()
		text={'hello':'Hello world!','name':'J','nowtime':now}
		return(text)


class get_accident_list(LoginRequiredMixin,ListView):
	model = accident
	template_name = "accident_list.html"
	context_object_name =  "accident_list"

		#return context

class get_term_list(LoginRequiredMixin,ListView):
	model = term
	template_name = "term_list.html"
	context_object_name =  "term_list"

class get_term_detail(LoginRequiredMixin,DetailView):
	template_name = "term.html"
	model = term
	context_object_name = "term"
	pk_url_kwarg = 'term_id'

class get_download(ListView):
    template_name = 'download.html'
    context_object_name =  'download'
    
    def get_queryset(self):
        now = datetime.datetime.now()
        text={'hello':'Hello world!','name':'J','nowtime':now}
        return(text)

employee/views.py
# Create your views here.
from django.shortcuts import render
from django.urls import reverse_lazy 
from django.views.generic.edit import CreateView 
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth import authenticate, login 
 
class EmployeeRegistrationView(CreateView): 
    template_name = 'employees/employee/registration.html' 
    form_class = UserCreationForm 
    success_url = reverse_lazy('employee_accident_list') 
 
    def form_valid(self, form): 
        result = super(EmployeeRegistrationView, self).form_valid(form) 
        cd = form.cleaned_data 
        user = authenticate(username=cd['username'], password=cd['password1']) 
        login(self.request, user) 
        return result

data_platform/templates/accident_list.html
{% load static %}
{% include "head.html" %}
<body>
<div class="ui sidebar inverted vertical menu">
    <a class="item" href="test2.html">
        <img class="ui avatar image" src="{% static 'images/icons/imac.svg' %}">
    &#8195;&#8194;监控面板
    </a>
    <a class="item">
        <img class="ui avatar image" src="{% static 'images/icons/clipboard.svg' %}">
      &#8195;&#8194;问题管理
    </a>
    <div class="item">
        <img class="ui avatar image" src="{% static 'images/icons/goal.svg' %}">
          &#8195;&#8194;我的任务
        <div class="menu">
              <a class="item">&#8195;&#8195;&#8195;&#8195;&#8195;待处理的任务</a>
              <a class="item">&#8195;&#8195;&#8195;&#8195;&#8195;已处理的任务</a>
        </div>
    </div>
</div>

<div class="ui main container">
    
    <div class="column">
        <div class="pusher">
           <div class="ui container">
           <div class="ui labeled icon button">
            <i class = "sidebar icon"></i>
            Menu
           </div>
           </div>
        </div>
            <div class="right item">
                <h3 class = "header">事故调查表</h3>
            </div>
        <div class="ui basic segment pushable">
            <button class="ui new blue button">
                <span style="font-size: 1em; color: white;">
                  <i class="fas fa-edit"></i>
                </span>
              &#8194;新建
            </button>
            <button class="ui renewal button">
                <span style="font-size: 1em; color: white;">
                    <i class="fas fa-redo"></i>
                </span>
              &#8194;刷新
            </button>
            <button class="ui download button">
                <span style="font-size: 1em; color: white;">
                    <i class="fas fa-angle-double-down"></i>
                </span>
              &#8194;下载
            </button>
          <table id="event" class="ui striped table">
              <thead>
              <tr>
                <th>事件名称</th>
                <th>发生时间</th>
                <th>事故机型</th>
                <th>详细情况</th>
              </tr>
              </thead>

              <tfoot>
                <tr>
                  <th>事件名称</th>
                  <th>发生时间</th>
                  <th>事故机型</th>
                  <th>详细情况</th>
                </tr>
              </tfoot>

              <tbody>
                {% for accident in accident_list %}
                  <tr>
                    <td>{{accident.title}}</td>
                    <td>{{accident.date}}</td>
                    <td>{{accident.acmodel}}</td>
                    <td>{{accident.content}}</td>
                 </tr>
               {% endfor %}
              </tbody>

          </table>

          <p>
            <button id="addRow">添加行</button>
            <button id="delRow">删除选中的行</button>
          </p>

        </div>
    </div>
</div> 
    

<!--     DataTables JS -->
    <script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
    <!--增删行列-->
    <!--增加行-->
    <script type="text/javascript">
      $(document).ready(function(){
        var table = $('#event').DataTable(); 
        i = table.rows.length;//或i=0;
        i++;//i指数据库的数据条数
        $('#addRow').on('click', function(){
            table.row.add([
            '<td><input type="Text" id="txt1' + i + '"/></td>',
            '<td><input type="Text" id="txt2' + i + '"/></td>',
            '<td><input type="Text" id="txt3' + i + '"/></td>',
            '<td><input type="Text" id="txt4' + i + '"/></td>'
            ]).draw();
        });
      });
    </script>
        
    <!--删除行-->
    <script type="text/javascript">
      $(document).ready(function(){
        var table = $('#event').DataTable(); 
        $('#event tbody').on('click','tr', function(){
            if ($(this).hasClass('selected')){
                $(this).removeClass('selected');
            }
            else{
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });
        $('#delRow').click(function(){
            table.row('.selected').remove().draw(false);
        });
      });
    </script>
    
    <!--分列查找内容-->
    <script type="text/javascript">
        $(document).ready(function() {
            // Setup - add a text input to each footer cell
            $('#event tfoot th').each( function () {
                var title = $('#event thead th').eq( $(this).index() ).text();
                $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
            });

            // DataTable
            var table = $('#event').DataTable();

            // Apply the search
            table.columns().eq( 0 ).each( function ( colIdx ) {
                $( 'input', table.column( colIdx ).footer() ).on( 'keyup change', function () {
                    table.column( colIdx ).search( this.value ).draw();
                });
            });
        });
    </script>
    <!--内嵌css代码-->
    <style type='text/css'>
        tfoot input {
        width: 100%;
        padding: 3px;
        box-sizing: border-box;
        }
    </style>
    
    <!--高亮鼠标停留的行和列-->
    <script type="text/javascript">   
        $(document).ready(function() {
            var lastIdx = null;
            var table = $('#event').DataTable();
            $('#event tbody')
                .on( 'mouseover', 'td', function () {
                    var colIdx = table.cell(this).index().column;
                    if ( colIdx !== lastIdx ) {
                        $( table.cells().nodes() ).removeClass( 'highlight' );
                        $( table.column( colIdx ).nodes() ).addClass( 'highlight' );
                    }
                } )
                .on( 'mouseleave', function () {
                    $( table.cells().nodes() ).removeClass( 'highlight' );
                } );
        } );
    </script>
    <style type="text/css">
        td.highlight {
            background-color: yellow!important;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function() {
           $('#event').DataTable({
               'scrollX':true,
               'scrollY':200,
               searching: true
           });
        });
        
//            $('#toggle').click(function(){               
//                $('.ui.sidebar').sidebar('toggle');
//            });
     
    </script>
    
  <script type="text/javascript">
    $('.ui.button').click(function(){

        $('.ui.sidebar').sidebar('toggle');
    });
</script>
</body>
{% include "foot.html" %}


<!-- 脚本部分用来处理表格样式等内容, 整个datatables用两个部分来控制, table部分控制数据和交互, script部分控制展试, 分页和搜索等功能-->

data_platform/templates/base.html
<!--Used by registraion/login.html-->
{% load staticfiles %} 
<!DOCTYPE html> 
<html> 
<head> 
    <meta charset="utf-8"/> 
    <title>{% block title %}Data-Platform{% endblock %}</title> 
    <link href="{% static "css/base.css" %}" rel="stylesheet"> 
</head> 
<body> 
<div id="header"> 
    <a href="/" class="logo">Data-Platform</a> 
    <ul class="menu"> 
        {% if request.user.is_authenticated %} 
            <li><a href="{% url "logout" %}">Sign out</a></li> 
        {% else %} 
            <li><a href="{% url "login" %}">Sign in</a></li> 
        {% endif %}
    </ul> 
</div> 
<div id="content"> 
    {% block content %} 
    {% endblock %} 
</div> 
<script> 
    $(document).ready(function () { 
        {% block domready %} 
        {% endblock %} 
    }); 
</script> 
</body> 
</html> 

data_platform/templates/foot.html
{% load static %}
<html>
<body>
  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">关于</h4>
          <div class="ui inverted link list">
            <a href="{% url 'data_platform:index' %}" class="item">Sitemap</a>
            <a href="{% url 'data_platform:index' %}" class="item">Contact Us</a>
            <a href="{% url 'data_platform:index' %}" class="item">Religious Ceremonies</a>
            <a href="{% url 'data_platform:index' %}" class="item">Gazebo Plans</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">服务</h4>
          <div class="ui inverted link list">
            <a href="{% url 'data_platform:index' %}" class="item">Banana Pre-Order</a>
            <a href="{% url 'data_platform:index' %}" class="item">DNA FAQ</a>
            <a href="{% url 'data_platform:index' %}" class="item">How To Access</a>
            <a href="{% url 'data_platform:index' %}" class="item">Favorite X-Men</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">页脚</h4>
          <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
        </div>
      </div>
    </div>
    <div class="ui center aligned container">
      <div class="ui inverted section divider"></div>
      <div style = "white-space:pre"><b>Copyright </b>© <b>2019-2022 中国商用飞机有限责任公司SIA工作组. </b>All rights reserved.</div>
    </div>
  </div>
  <!--[if lt IE 8]>
  <script src="js/icon-font-ie7.js"></script>
  <script src="js/icon-font-ie7-24.js"></script>
  <![endif]-->
</body>
</html>

data_platform/templates/head.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <title>*****D  A  T  A*****</title>
  <!-- Loading semantic_ui and datatables plug-ins================================-->
  <link href="{% static 'dist/semantic.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/datatables.min.css' %}" rel = "stylesheet">
  <link rel="stylesheet"href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <script type="text/javascript" src="{% static 'js/jquery.dataTables.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script><script type="text/javascript" src="{% static 'dist/semantic.min.js' %}"></script>
  
<!--  <script type="text/javascript" src="{% static 'js/dataTables.scroller.min.js"></script>-->
  <!--[if lt IE 9]>
    <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <style type="text/css">
    body {
      background-color: #FFFFFF;
    }
    .ui.menu .item img.logo {
      margin-right: 1.5em;
    }
    .main.container {
      margin-top: 7em;
    }
    .wireframe {
      margin-top: 2em;
    }
    .ui.footer.segment {
      margin: 5em 0em 0em;
      padding: 5em 0em;
    }
    .ui.container > h1 {
      font-size: 3em;
      text-align: center;
      font-weight: normal;
    }
  </style>
</head>
<body> 
  <div class="ui fixed primary  menu">
    <div class="ui container">
      <a href="{% url 'data_platform:index' %}" class="header item">
        <img class="logo" src="{% static 'logo.png' %}">
          特性Big Data
      </a>
      <a href="{% url 'data_platform:accident_list' %}" class="item">事故事件</a>
      <a href="{% url 'data_platform:term_list' %}" class="item">术语定义</a>
      <a href="{% url 'data_platform:download' %}" class="item">下载</a>
      {% if request.user.is_authenticated %} 
            <a href="{% url "logout" %}" class="right item">Sign out</a> 
      {% else %} 
            <a href="{% url "login" %}" class="right item">Sign in</a>  
      {% endif %}
    </div>
    <div class="ui action icon input">
      <input type="text" placeholder="搜索...">
      <i class="inverted circular search link icon"></i>
    </div>
  </div>

data_platform/templates/index.html
{% load static %}
{% include "head.html" %}
  <div class="ui main container">
    <h1>特性工程大数据平台</h1>
    <div class="ui text container">
      <p>特性工程大数据平台提供特性工程各专业在型号研制全寿命周期中的数据基础.</p>
      <p>现在是: {{ text.nowtime | date }} </p>
      <p>欢迎...</p>
      <button class = "ui blue button" onclick="location.href='{% url 'data_platform:accident_list' %}'" type = "button">了解更多</button>
    </div>
    <div class="ui raised very padded grid center">
      <div class="two wide column"></div>
      <div class="four wide column">
        <div class="ui raised card">
          <div class="content">
            <div class="header"><a href="{% url 'data_platform:accident_list' %}" class="item">事故事件</a></div>
            <div class="ui test container">相似机型运营数据, 事故事件数据, 及其他参考数据资料</div>
            <div class="meta">
              <span class="category">SIA</span>
            </div>
            <div class="description">
              <p></p>
            </div>
          </div>
          <div class="extra content">
            <div class="right floated author">
              <img class="ui avatar image" src="{% static 'images/login/icon.png' %}"> SIA
            </div>
          </div>
        </div>
      </div>
      <div class="four wide column">
        <div class="ui raised card">
            <div class="content">
              <div class="header">型号设计</div>
              <div class="ui test container">型号设计数据<br/><br/></div>
              <div class="meta">
                <span class="category">SIA</span>
                <img class="ui avatar image" src="{% static 'images/login/icon.png' %}"> SIA
              </div>
            </div>
        </div>
      </div>
      <div class="four wide column">
        <div class="ui raised card">
          <div class="content">
            <div class="header"><a href="{% url 'data_platform:term_list' %}" class="item">术语定义</a></div>
            <div class="ui test container">型号常用术语, 定义, 缩略语<br/><br/></div>
            <div class="meta">
              <span class="category">SIA</span>
            </div>
            <div class="description">
              <p></p>
            </div>
          </div>
          <div class="extra content">
            <div class="right floated author">
              <img class="ui avatar image" src="{% static 'images/login/icon.png' %}"> SIA
            </div>
          </div>
        </div>
      </div>
      <div class="two wide column"></div>
    </div>
    <p><strong class="Afghanistan flag"> </strong></p>
  </div>
{% include "foot.html" %}
<!--以下是只在本页面中适用的css和js等内容-->
<style type="text/css">
  .ui.text.container  {
    text-align: center;
    font-weight: normal;
  }
</style>

data_platform/templates/page.html
{% load static %}
{% include "head.html" %}

<div class="ui main text container">
  <div>
  <h3 class="ui header">
    文章列表
  </h3>
  {% for article in article_list %}
  <div class="blog-post">
    <h2>
      <a class="text-dark" href="{% url 'blog:detail' article.id %}">{{article.title}}</a>
    </h2>
    <hr>
    <div>
      <p>{{ article.content | striptags |truncatewords:20}}</p>
    </div>
  </div>
  {% endfor %}
  </div>
</div>

{% include "foot.html" %}

data_platform/templates/search_form.html
{% include "head.html" %}
      <div class="container bs-docs-container">
        <div class="demo-headline">
          <h1 class="demo-logo">
            <div class="logo"></div>
            Thelalasis
            <small>马彪的个人主页</small>
          </h1>
        </div> <!-- /demo-headline -->

        <!-- Static navbar -->
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
          <form action="/search" method="post">
            {% csrf_token %}
            <input type="text" name="q">
            <input type="submit" value="搜索">
          </form>
          <p>{{rlt}}</p>
          <p>{{ttt}}</p>
        </div>
      </div> <!-- /container -->
{% include "foot.html" %}

data_platform/templates/term.html
{% load static %}
{% include "head.html" %}
<div class="ui main text container"> 
    <div class="ui grid">
        <div class="four wide column left floated">
            <div class="ui animated button" tabindex="0">
              <div class="visible content">返回</div>
              <div class="hidden content">
                <a href="{% url 'data_platform:term_list' %}"><i class="left arrow icon"></i></a>
              </div>
            </div>
        </div>
        <div class="eight wide column right floated">
          <h2 class="ui header">
            <div class="column"><i class="book icon"></i>{{term.title}}</div>
          </h2>
        </div>
        <div class="ten wide column">
            {% for tag in term.tag.all %}
            <a class="ui teal tag label">{{tag}}</a>
            {% endfor %}
        </div>
    </div> 

    <div class="ui divider"></div>
    <div class="ui raised very padded text container segment">
      <h3>相关型号</h3>
      <button class="ui inverted red button">{{term.acmodel}}</button>
    </div>
    <div class="ui raised very padded text container segment">
      <h3>词条解释</h3>
      <p>{{term.content | safe}}</p>
    </div>
  </div>
  <div class="ui raised very padded text container segment">
      <h3>词条来源</h3>
      <p>{{term.source | safe}}</p>
    </div>
{% include "foot.html" %}

data_platform/templates/term_list.html
{% load static %}
{% include "head.html" %}

<div class="ui invisible inverted left vertical sidebar menu">
        <a class="item">
            <img class="ui avatar image" src="{% static 'images/icons/imac.svg' %}">
          &#8195;&#8194;监控面板
        </a>
        <a class="item">
            <img class="ui avatar image" src="{% static 'images/icons/clipboard.svg' %}">
          &#8195;&#8194;问题管理
        </a>
        <div class="item">
            <img class="ui avatar image" src="{% static 'images/icons/goal.svg' %}">
              &#8195;&#8194;我的任务
            <div class="menu">
                  <a class="item">&#8195;&#8195;&#8195;&#8195;&#8195;待处理的任务</a>
                  <a class="item">&#8195;&#8195;&#8195;&#8195;&#8195;已处理的任务</a>
            </div>
        </div>
</div>

<div class="ui main container">
    <div class="column">
      <div class="pusher">
           <div class="ui container">
           <div class="ui labeled icon button">
            <i class = "sidebar icon"></i>
            Menu
           </div>
           </div>
        </div>
            <div class="left item">
                <h3 class = "header">事故调查表</h3>
            </div>
    </div>
    <div class="ui bottom attached segment pushable">
      
      <div class="pusher">
        <div class="ui basic segment">
            <button class="ui new blue button">
                <span style="font-size: 1em; color: white;">
                  <i class="fas fa-edit"></i>
                </span>
              &#8194;新建
            </button>
            <button class="ui renewal button">
                <span style="font-size: 1em; color: white;">
                    <i class="fas fa-redo"></i>
                </span>
              &#8194;刷新
            </button>
            <button class="ui download button">
                <span style="font-size: 1em; color: white;">
                    <i class="fas fa-angle-double-down"></i>
                </span>
              &#8194;下载
            </button>
          <table id="event" class="ui striped table">
              <thead>
              <tr>
                <th>术语</th>
                <th>适用机型</th>
                <th>术语说明</th>
              </tr>
              </thead>
              <tfoot>
              <tr>
                <th>术语</th>
                <th>适用机型</th>
                <th>术语说明</th>
              </tr>
              </tfoot>
              <tbody>
                  {% for term in term_list %}
                      <tr>
                        <td><a class="text-dark" href="{% url 'data_platform:term_detail' term.id %}">{{term.title}}</a></td>
                        <td>{{term.acmodel}}</td>
                        <td>{{term.content | striptags |truncatewords:20}}</td>
                      </tr>
                  {% endfor %}
              </tbody>

          </table>
            
          <p>
            <button id="addRow">添加行</button>
            <button id="delRow">删除选中的行</button>
          </p>
        
        </div>
      </div>
    </div>    
</div>


<script type="text/javascript" charset="utf8" src="http://cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
    <!--增删行列-->
    <!--增加行-->
    <script type="text/javascript">
      $(document).ready(function(){
        var table = $('#event').DataTable(); 
        i = table.rows.length;//或i=0;
        i++;//i指数据库的数据条数
        $('#addRow').on('click', function(){
            table.row.add([
            '<td><input type="Text" id="txt1' + i + '"/></td>',
            '<td><input type="Text" id="txt2' + i + '"/></td>',
            '<td><input type="Text" id="txt3' + i + '"/></td>'
            ]).draw();
        });
      });
   </script>
        
    <!--删除行-->
    <script type="text/javascript">
      $(document).ready(function(){
        var table = $('#event').DataTable(); 
        $('#event tbody').on('click','tr', function(){
            if ($(this).hasClass('selected')){
                $(this).removeClass('selected');
            }
            else{
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });
        $('#delRow').click(function(){
            table.row('.selected').remove().draw(false);
        });
      });
    </script>
    
    <!--分列查找内容-->
    <script type="text/javascript">
        $(document).ready(function() {
            // Setup - add a text input to each footer cell
            $('#event tfoot th').each( function () {
                var title = $('#event thead th').eq( $(this).index() ).text();
                $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
            });

            // DataTable
            var table = $('#event').DataTable();

            // Apply the search
            table.columns().eq( 0 ).each( function ( colIdx ) {
                $( 'input', table.column( colIdx ).footer() ).on( 'keyup change', function () {
                    table.column( colIdx ).search( this.value ).draw();
                });
            });
        });
    </script>
    <!--内嵌css代码-->
    <style type='text/css'>
        tfoot input {
        width: 100%;
        padding: 3px;
        box-sizing: border-box;
        }
    </style>
    
    <!--高亮鼠标停留的行和列-->
    <script type="text/javascript">   
        $(document).ready(function() {
            var lastIdx = null;
            var table = $('#event').DataTable();
            $('#event tbody')
                .on( 'mouseover', 'td', function () {
                    var colIdx = table.cell(this).index().column;
                    if ( colIdx !== lastIdx ) {
                        $( table.cells().nodes() ).removeClass( 'highlight' );
                        $( table.column( colIdx ).nodes() ).addClass( 'highlight' );
                    }
                } )
                .on( 'mouseleave', function () {
                    $( table.cells().nodes() ).removeClass( 'highlight' );
                } );
        } );
    </script>
    <style type="text/css">
        td.highlight {
            background-color: yellow!important;
        }
    </style>

{% include "foot.html" %}
<!--以下是本页适用的脚本-->
<script type="text/javascript">
  function filterGlobal () {
  $('#example').DataTable().search(
      $('#global_filter').val(),
      $('#global_regex').prop('checked'),
      $('#global_smart').prop('checked')
  ).draw();
  }

  function filterColumn ( i ) {
  $('#example').DataTable().column( i ).search(
      $('#col'+i+'_filter').val(),
      $('#col'+i+'_regex').prop('checked'),
      $('#col'+i+'_smart').prop('checked')
  ).draw();
  }
  $(document).ready(function() {
     $('#event').DataTable({
         'scrollX':true,
         'scrollY':200,
         searching: true,
     });
     $('input.global_filter').on( 'keyup click', function () {
      filterGlobal();
    } );

     $('input.column_filter').on( 'keyup click', function () {
      filterColumn( $(this).parents('tr').attr('data-column') );
    } );});
  </script>
<!-- 脚本部分用来处理表格样式等内容, 整个datatables用两个部分来控制, table部分控制数据和交互, script部分控制展试, 分页和搜索等功能-->

<script type="text/javascript">
    $('.ui.button').click(function(){

        $('.ui.sidebar').sidebar('toggle');
    });
</script>
  